### ISSUE TITLE
バイナリをリリースしてくれませんか？

### ISSUE THREAD

**Issue by KeitoTobi1** [dragoon2014/dxlib-d#1]
DXライブラリの最新版に対応しているのと、従来のDXライブラリ+D言語と互換性があるのはいいのですが、
なぜ、インストールする際にはVisual C++のリンカーを使ってまでコンパイルしなければならないのでしょうか？
せめてバイナリをリリースして、Visual C++のリンカーを使わなくてもコンパイルできるようにしてくれませんか？
そこら辺は、よろしくお願いします。
また、バイナリをリリースする時はDUBにも登録しておいてください。

**Comment by dragoon2014** [comment]
> なぜ、インストールする際にはVisual C++のリンカーを使ってまでコンパイルしなければならないのでしょうか？
> せめてバイナリをリリースして、Visual C++のリンカーを使わなくてもコンパイルできるようにしてくれませんか？

インポートライブラリが欲しいということでしょうか。
DXライブラリのDLLを利用する方式には対応していません。
また、積極的に対応する予定も今の所ありません。

DXライブラリ本家が提供している他の静的リンク用のライブラリについては
dmd付属のリンカが対応していない（はずの）ため使用できません。
DXライブラリをdmcなどでコンパイルしなおすか
mingw-gcc向けライブラリ+gdcなどで使用できるかもしれませんが試していません。
VCのリンカを使わずに、dmc以外で作られたC言語のライブラリをリンクする手段があれば教えていただきたいです。


> DUBにも登録しておいてください。

DUBへのアップについては検討します。

**Comment by KeitoTobi1** [comment]
DXライブラリをdmcでコンパイルですか…。
とりあえずまあ、それを試してみてはいかがでしょうか？
それができたら報告等はお願いしますね。
